### ISSUE TITLE
test data

### ISSUE THREAD

**Issue by visr** [yeesian/ArchGDAL.jl#10]
Great to have the extensive testing, but 200MB of data is quite a lot for a Julia package. Perhaps it'd be good to put the data in a separate repository (`ArchGDALData`), that is in the `test/REQUIRE` only?

The bulk comes from 2 83MB rasters.
`test/ospy/data4/aster.img`
`test/ospy/data5/aster.img`

**Comment by yeesian** [comment]
Yeah, I was thinking of creating `GDALBenchmarks.jl` for running it against larger files, and sticking to only small data files for this repository.

**Comment by evetion** [comment]
We could set this up like [TestImages.jl](https://github.com/JuliaImages/TestImages.jl/blob/master/src/TestImages.jl), which downloads requested images from their hosted github-pages branch. In that way, the package remains small. Explanation [here](https://juliaimages.github.io/TestImages.jl/).

Also, for naming, I suggest something with ArchGDAL in the name.

**Comment by yeesian** [comment]
Yeah sure! I haven't had the time to get to it, and am mostly unsure of how to scrub it from the .git history. Might you be able to help here?

I also don't mind if we do not turn the datasets into a full julia package, and just host the files somewhere for now.

**Comment by evetion** [comment]
For scrubbing large files I would try this: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by yeesian** [comment]
Following the instructions, on current master:

```
$ java -jar bfg-1.13.0.jar --strip-blobs-bigger-than 5M ArchGDAL.jl.git

Using repo : /Users/yeesian/Github_Repos/ArchGDAL.jl.git

Scanning packfile for large blobs: 868
Scanning packfile for large blobs completed in 52 ms.
Found 7 blob ids for large blobs - biggest=86741380 smallest=5615222
Total size (unpacked)=139310052
Found 49 objects to protect
Found 28 commit-pointing refs : HEAD, refs/heads/datastreams, refs/heads/docs, ...

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

 * commit ed68596a (protected by 'HEAD')

Cleaning
--------

Found 144 commits
Cleaning commits:       100% (144/144)
Cleaning commits completed in 768 ms.

Updating 27 Refs
----------------

	Ref                      Before     After
	--------------------------------------------
	refs/heads/datastreams | 01b67091 | 5a4a3948
	refs/heads/docs        | 1a19f8d5 | bee2fcf3
	refs/heads/fix-gdal    | 1f4e5f9c | 1862ea31
	refs/heads/master      | ed68596a | 36544b3e
	refs/heads/plotrecipes | 6bc77ff5 | efd0d12c
	refs/heads/spatialite  | a87e9beb | 1bd470d6
	refs/pull/1/head       | 0a6a39a9 | 24a1e685
	refs/pull/12/head      | 62ced917 | a4f9e790
	refs/pull/13/head      | ac1a6a0a | 0655a1cb
	refs/pull/14/head      | 18581e6f | 6a6d64b3
	refs/pull/15/head      | 8dbd2b85 | 45cef603
	refs/pull/16/head      | 7ba507b5 | 0b6f4848
	refs/pull/18/head      | d002163b | 08f10415
	refs/pull/2/head       | ba4e7423 | fc68f8ab
	refs/pull/20/head      | f11904fe | 8a48bf8a
	...

Updating references:    100% (27/27)
...Ref update completed in 77 ms.

Commit Tree-Dirt History
------------------------

	Earliest                                              Latest
	|                                                          |
	DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDm

	D = dirty commits (file tree fixed)
	m = modified commits (commit message or parents changed)
	. = clean commits (no changes to file tree)

	                        Before     After
	-------------------------------------------
	First modified commit | be80fe5e | 3fc10f40
	Last dirty commit     | 1f4e5f9c | 1862ea31

Deleted files
-------------

	Filename            Git id
	--------------------------------------
	aster.img         | 5149027e (82.7 MB)
	aster.rrd         | 6204be5a (7.3 MB)
	cookbook-data.zip | f5cc99d0 (9.6 MB)
	doq1.img          | c014411c (13.1 MB)
	doq2.img          | bf56ac54 (5.4 MB)
	test-2.3.sqlite   | e1759a3e (6.6 MB)
	world.tif         | 8e72bf64 (8.2 MB)


In total, 322 object ids were changed. Full details are logged here:

	/Users/yeesian/Github_Repos/ArchGDAL.jl.git.bfg-report/2018-03-26/23-52-41

BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive


--
You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, to make people give up on ever
being told the truth. Don't give up: https://github.com/bkeepers/stop-trump
--
```

and the size on disk went down from 70.6MB to 2.7MB.

I haven't yet pushed the small version to github. Might it conflict with your PR etc?

**Comment by yeesian** [comment]
@visr @evetion 

I have just ran the BFG and pushed the changes. Now's a good time for you to delete your current copies of ArchGDAL and do fresh clones (they should only be about 1.4MB):

> At this point, you're ready for everyone to ditch their old copies of the repo and do fresh clones of the nice, new pristine data. It's best to delete all old clones, as they'll have dirty history that you don't want to risk pushing back into your newly cleaned repo.

**Comment by evetion** [comment]
```
➜ du -sh ArchGDAL
1.4M	ArchGDAL
```
Nice!

**Comment by visr** [comment]
Great, thanks, I'll do that!
