### ISSUE TITLE
specifying geotif compression when writing?

### ISSUE THREAD

**Issue by rafaqz** [yeesian/ArchGDAL.jl#109]
It would be good if it was easy to pass “COMPRESS=LZW” or similar. Is it possible currently?

**Comment by evetion** [comment]
Sure! Pass it as options to the `create` method. An example in my own `GeoArrays` package, where I enable it by default for geotiffs: https://github.com/evetion/GeoArrays.jl/blob/master/src/io.jl#L69

**Comment by rafaqz** [comment]
thanks!
