### ISSUE TITLE
Should we provide our own data-types?

### ISSUE THREAD

**Issue by yeesian** [yeesian/ArchGDAL.jl#11]
Currently this package does not provide any data abstractions for handles to GDAL objects, and makes it the responsibility of the user.

It uses the [`unsafe` prefix](http://docs.julialang.org/en/release-0.4/manual/style-guide/#don-t-expose-unsafe-operations-at-the-interface-level) for methods that returns objects that needs to be destroyed:
```julia
julia> AG.unsafe_
unsafe_boundary                   unsafe_createmultipoint            unsafe_fromWKB
unsafe_buffer                     unsafe_createmultipolygon          unsafe_fromWKT
unsafe_centroid                   unsafe_createmultipolygon_noholes  unsafe_fromXML
unsafe_clone                      unsafe_createpoint                 unsafe_getcurvegeom
unsafe_convexhull                 unsafe_createpolygon               unsafe_getfeature
unsafe_create                     unsafe_createstylemanager          unsafe_getlineargeom
unsafe_createRAT                  unsafe_createstyletable            unsafe_intersection
unsafe_createcolortable           unsafe_createstyletool             unsafe_loadstringlist
unsafe_createcoordtrans           unsafe_delaunaytriangulation       unsafe_newspatialref
unsafe_createcopy                 unsafe_difference                  unsafe_nextfeature
unsafe_createfeature              unsafe_executesql                  unsafe_pointalongline
unsafe_createfeaturedefn          unsafe_forceto                     unsafe_pointonsurface
unsafe_createfielddefn            unsafe_fromEPSG                    unsafe_polygonfromedges
unsafe_creategeom                 unsafe_fromEPSGA                   unsafe_polygonize
unsafe_creategeomcollection       unsafe_fromESRI                    unsafe_read
unsafe_creategeomfielddefn        unsafe_fromGML                     unsafe_symdifference
unsafe_createlinearring           unsafe_fromJSON                    unsafe_union
unsafe_createlinestring           unsafe_fromPROJ4                   unsafe_update
unsafe_createmultilinestring      unsafe_fromURL
```
and [`do`-blocks as context managers](https://github.com/yeesian/ArchGDAL.jl/blob/3a0b0011e7180ff3eea140228a153afd01ec63ad/src/context.jl).

I have also committed to the [(questionable) decision](http://docs.julialang.org/en/release-0.4/manual/style-guide/#don-t-overload-methods-of-base-container-types) of overloading the display methods for a nicer user-experience (like in the README).

Unfortunately, that means that user code which "leaks" the handles outside the do-block managers will likely result in a segfault:

```julia
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> import ArchGDAL; const AG = ArchGDAL
ArchGDAL

julia> AG.registerdrivers() do
       AG.read("data/point.geojson") do dataset
       dataset
       end
       end
Segmentation fault: 11
```
Since the [display methods](https://github.com/yeesian/ArchGDAL.jl/blob/3a0b0011e7180ff3eea140228a153afd01ec63ad/src/base/display.jl) will call GDAL methods on an object that has been destroyed.

### Some Possible Resolutions
1. make the do-block context managers return `true`/`false` to indicate success/failure.
2. provide corresponding data-types in this package, e.g.
```julia
type FeatureLayer
    ptr::Ptr{GDAL.OGRLayerH}
    ...
end
```
that will provide methods that set `obj.ptr` to `C_NULL` after destroying the GDAL object corresponding to `obj::FeatureLayer`.

ping @visr @meggart

### Miscellaneous Remarks
To anticipate some suggestion(s): this package will not be providing finalizers that calls GDAL's `destroy` on the objects, as it [does not mix well with a style of programming that makes it the responsibility of the user to manage memory](https://trac.osgeo.org/gdal/wiki/PythonGotchas#CertainobjectscontainaDestroymethodbutyoushouldneveruseit), and users expecting it should look for other packages (e.g. [GeoDataFrames](https://github.com/yeesian/GeoDataFrames.jl)).

**Comment by visr** [comment]
Thanks for the writeup. Still trying to wrap my head around it.

So in [Even's mail](http://lists.osgeo.org/pipermail/gdal-dev/2010-September/026027.html) it says:
> Native object gets destroyed when Python object goes out of scope, or when they are assigned to None. So replace foo.Destroy() by foo = None if you really want to control when the underlying C++ object is destroyed.

This is not the case for GDAL.jl right? As I understood, the memory is controlled by C, so it won't be collected by the julia GC. Is it possible to own the pointers such that we can let the julia GC take care of them?

**Comment by yeesian** [comment]
> This is not the case for GDAL.jl right?

Yeah, this is not the case for `GDAL.jl`.

> Is it possible to own the pointers such that we can let the julia GC take care of them?

Yes, it is, if we provide finalizers that calls `destroy()` on the objects, e.g. see how it is done in [LibGEOS.jl](https://github.com/JuliaGeo/LibGEOS.jl/blob/efe733d9b473d8b25fe7ddb4cd688464df7e8542/src/geos_types.jl).
