### ISSUE TITLE
Register Drivers Function Doesn't Seem To Work

### ISSUE THREAD

**Issue by MattCanada** [yeesian/ArchGDAL.jl#115]
Hello All,

This is my first crack at using Julia, and I'm having trouble getting my tool to work with ArchGDAL. The tool is supposed to read an input raster (1.tif), and use its pixel size to multiply the values in each pixel, then output the result in a new tif (2.tif). The following works so far:

```
using ArchGDAL; const jdal = ArchGDAL
inf = jdal.read("C:/Users/info/Desktop/1.tif")
nrow = jdal.height(inf)  
ncol = jdal.width(inf)
nsize = *(ncol,nrow)
gt = jdal.getgeotransform(inf)
xy = gt[2]
inb = jdal.getband(inf,1)
ina = jdal.read(inb)
oua = ina*xy
oua = convert(Array{Float32,2}, oua)
```
But now that I want to actually write the result array (oua) to a new raster, I cannot get this section below to work, even after research! The compiler throws a ```ERROR: UndefVarError: registerdrivers not defined``` message. But I thought registerdrivers() worked?

```
jdal.registerdrivers() do
dataset = jdal.create("C:/Users/info/Desktop/2.tif", jdal.getdriver("GTiff"), width=ncol, height=nrow, nbands=1, dtype=Float32)
dataset = jdal.write(dataset, oua, 1)
end
```

Has something happened with registerdrivers(), or is there something I'm omitting from my tool? Any help or clarity would be great -

**Comment by visr** [comment]
Hi, welcome :)

From where did you get that you have to use registerdrivers? It is no longer necessary, since it is now done as the ArchGDAL module loads. Does it work if you leave it out?

**Comment by MattCanada** [comment]
Hi @visr,
Thanks,

Unfortunately it doesn't work just yet when take the registerdriver() out. This line is giving me errors:
`blanktif = jdal.create("C:/Users/info/Desktop/2.tif", jdal.getdriver("GTiff"), width=ncol, height=nrow, nbands=1, dtype=Float32)`

The result is:

`ERROR: MethodError: no method matching create(::String, ::ArchGDAL.Driver; width=1731, height=1153, nbands=1, dtype=Float32)
Closest candidates are:
  create(::AbstractString; driver, width, height, nbands, dtype, options) at C:\Users\info\.julia\packages\ArchGDAL\JhHWz\src\dataset.jl:258`

I looked through some of documentation and I thought I filled in the arguments correctly for the ArchGDAL create function. I'm thinking the string type for the filename is wrong somehow... I'm not exactly sure what I am doing wrong!

Cheers,

**Comment by evetion** [comment]
You can take a look at the implementation in [this package](https://github.com/evetion/GeoArrays.jl/blob/master/src/io.jl) for an example (disclosure, the linked package is my own).

**Comment by visr** [comment]
It seems that the problem with the `ArchGDAL.create` call is that the driver has to be passed as a keyword argument as well, this works:

```julia
julia> using ArchGDAL; ArchGDAL.create("test.tif", driver=ArchGDAL.getdriver("GTiff"), width=20, height=10, nbands=1, dtype=Float32)
GDAL Dataset (Driver: GTiff/GeoTIFF)
File(s):
  test.tif

Dataset (width x height): 20 x 10 (pixels)
Number of raster bands: 1
  [GA_Update] Band 1 (Gray): 20 x 10 (Float32)
```

I see that the examples at http://yeesian.com/ArchGDAL.jl/latest/reference/#ArchGDAL.create-Tuple{AbstractString} don't work, we should update them.

**Comment by MattCanada** [comment]
Hi @visr 

I got your solution to work! Thank you and @evetion for your help!
I guess `using ArchGDAL; ArchGDAL.create( ... )` is the current way of doing it

**Comment by visr** [comment]
Great, glad it's working. In d01cb3680c4afa81e374ebfb22a7b516ee2537ec I attempted to clarify it a little in the example, will close the issue with that.
