### ISSUE TITLE
ArchGDAL.getproj(dataset) return empty string,  while dataset.GetProjection() retrun string "PROJCS[...]"  using gdal in python

### ISSUE THREAD

**Issue by lanyouguo** [yeesian/ArchGDAL.jl#116]
I want to extract longitudes and latitudes from Geotiff File. I used the ArchGDAL as follow:
`using ArchGDAL`
`AG=ArchGDAL`
`fname="1.TIFF"`
`dataset = AG.read(fname)`
`AG.getproj(dataset)`
the code above return empty string.

I used gdal in python return the right string "PROJCS[...]", the python code as follow:
`from osgeo import gdal`
`fname="1.TIFF"`
`dataset = gdal.Open(tifFile)`
`dataset.GetProjection()`

I used the python package rasterio, `dataset.crs` also get the right string.

I have no idea why ArchGDAL.getproj(ds) cann't get the same result as in python.

**Comment by visr** [comment]
Hmm if I try this out on a random file with CRS, it works for me, and it's also covered by the tests. What Julia and ArchGDAL version are you on, and is it possible to share the "1.TIFF" file?

**Comment by lanyouguo** [comment]
I use julia version 1.4 and and ArchGDAL v0.3.1.  When I first run the code `AG.getproj(dataset)`, it returns error message:
`GDALError (CE_Failure, code 1):
	PROJ: proj_create_from_database: ellipsoid not found`

When I run the code  `AG.getproj(dataset)` again, it returns the empty string. It's very strange.

I run `gdalinfo 1.TIFF` in the command line, message as follow:
```Driver: GTiff/GeoTIFF
Files: 1.tiff
Size is 13533, 10394
Warning 1: Cannot find ellipsoid.csv
Coordinate System is:
PROJCS["Projection Name = UTMUnits = Meter",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["unnamed",6378137,298.2571643544928],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",15.0346676474245],
    PARAMETER["central_meridian",128.8565357598851],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",4000000],
    PARAMETER["false_northing",1000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]
Origin = (3695222.288723240140826,1217060.711786244064569)
Pixel Size = (40.000000000000000,-40.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 3695222.289, 1217060.712) (125d59'40.53"E, 16d58'36.76"N)
Lower Left  ( 3695222.289,  801300.712) (126d 2'40.19"E, 13d13'21.26"N)
Upper Right ( 4236542.289, 1217060.712) (131d 4'41.27"E, 16d59' 5.52"N)
Lower Right ( 4236542.289,  801300.712) (131d 2'21.73"E, 13d13'43.40"N)
Center      ( 3965882.289, 1009180.712) (128d32'20.44"E, 15d 7' 2.82"N)
Band 1 Block=13533x1 Type=UInt16, ColorInterp=Gray```

**Comment by lanyouguo** [comment]
Sorry for closing the issue inadvertently . So I reopenit

**Comment by visr** [comment]
So it appears that both the command line and julia package have the same issue, except that the command line gives it as a warning whereas julia throws an error:

```
GDALError (CE_Failure, code 1): PROJ: proj_create_from_database: ellipsoid not found
```

The `ellipsoid.csv` file is indeed not present in the artifacts. Could it be some issue with a certain kind of projection that is not supported in the new GDAL & PROJ versions? I don't think there is much we can do in this repository.

**Comment by evetion** [comment]
Could you try to see what happens if you downgrade GDAL to 1.0.2? (`]add GDAL@1.0.2`)

**Comment by lanyouguo** [comment]
The current version of GDAL is v1.1.0.  
I use the the command `]add GDAL@1.0.2`,  then run the code `using ArchGDAL`, and get the error message "GDAL not intalled properly". 
So I use `Pkg.build("GDAL")`,  error again, and I cann't finish the building. 
I used the same code last year, and I get the right string`"PROJCS[]"`. Maybe it's related to the version of GDAL.

**Comment by lanyouguo** [comment]
> So it appears that both the command line and julia package have the same issue, except that the command line gives it as a warning whereas julia throws an error:
> 
> ```
> GDALError (CE_Failure, code 1): PROJ: proj_create_from_database: ellipsoid not found
> ```
> 
> The `ellipsoid.csv` file is indeed not present in the artifacts. Could it be some issue with a certain kind of projection that is not supported in the new GDAL & PROJ versions? I don't think there is much we can do in this repository.

Maybe you are right.  I used the same code last year, and I get the right string"PROJCS[]". Maybe it's related to the version of GDAL.
