### ISSUE TITLE
Travis CI not running on PRs?

### ISSUE THREAD

**Issue by visr** [yeesian/ArchGDAL.jl#122]
I noticed in #120 that only the Appveyor CI status is shown.
Travis CI is still running on master as seen from https://travis-ci.org/github/yeesian/ArchGDAL.jl, and ran for branches up to 1 month ago. Needs investigation.

**Comment by rafaqz** [comment]
Yeah I noticed that too. Could be the "Build pushed pull requests" toglle on the travis settings page.

Travis has windows now too so appveyor may as well be removed.

**Comment by visr** [comment]
@yeesian any change you could confirm the setting Rafael mentioned? I cannot access the settings.

**Comment by yeesian** [comment]
> Could be the "Build pushed pull requests" toglle on the travis settings page.

Ah yup it was! Thanks for pointing it out and pinging me! Sorry it took me so long to respond
