### ISSUE TITLE
online docs are old

### ISSUE THREAD

**Issue by visr** [yeesian/ArchGDAL.jl#134]
https://yeesian.com/ArchGDAL.jl/stable/ seems to be v0.3.1, that should be v0.5.0. Not sure why

There hasn't been a commit on gh-pages for a long time: https://github.com/yeesian/ArchGDAL.jl/tree/gh-pages

With the doc updates in c22481854e3dfce16070d8b379de151dbbcf39a0 at least my local doc build was working again, but there are seemingly other issues also.

We probably need to go over https://juliadocs.github.io/Documenter.jl/stable/man/hosting/ and make sure things are ok. Can't verify if the DOCUMENTER_KEY secret is set though.

**Comment by yeesian** [comment]
Cool thanks for the issue and the links! It seems that

1. We should remove `matrix` from travis.yml

> Travis CI used to use matrix: as the section to configure to build matrix in the config file. This now appears to be a deprecated alias for jobs:. If you use both matrix: and jobs: in your configuration, matrix: overrides the settings under jobs:.
>
> If your .travis.yml file still uses matrix:, it should be replaced with a a single jobs: section.

2. Is the preference for us to deploy using "Travis CI" or "GitHub Actions"?

**Comment by visr** [comment]
Closing. This is now updated: https://yeesian.com/ArchGDAL.jl/dev/
This is still old: https://yeesian.com/ArchGDAL.jl/stable/
But that is because the setup was broken when v0.5.0 was tagged. Not sure if we can force it to rebuild, but if needed we can tag v0.5.1 for this, or just wait until we do that anyway.

**Comment by felixcremer** [comment]
I think we could push a 0.5.0+doc1 tag to github,  from the fixed travis commit so that the docs would be rebuilt as the Documenter.jl docs say:

> In this situation, you can manually create and push a tag for the commit with the fix that has the same version number, but also some build metadata (e.g. v1.2.3+doc1). For Git, this is a completely different tag, so it won't interfere with anything. But when Documenter runs on this tag, it will ignore the build metadata and deploy the docs as if they were for version v1.2.3.

**Comment by visr** [comment]
Cool, didn't know about that trick! Just pushed the tag, building now: https://travis-ci.org/github/yeesian/ArchGDAL.jl/builds/720804526.

**Comment by visr** [comment]
Reopening since the docs still don't seem to be updated automatically. v0.5.0 was the last one due to the manual action, but since v0.5.1 and v0.5.2 have been released, and the stable docs are still from v0.5.0. For example, this section is currently not visible in the stable docs: https://yeesian.com/ArchGDAL.jl/dev/tables/.
