### ISSUE TITLE
Test Tables for geopackage and shapefile 

### ISSUE THREAD

**Issue by Sov-trotter** [yeesian/ArchGDAL.jl#141]
It's be nice to add tests for .shp and .gpkg files too. https://github.com/yeesian/ArchGDAL.jl/pull/118#issuecomment-684801782

**Comment by Sov-trotter** [comment]
@yeesian could you add the `goodfirstissue` and `Hacktoberfest` tags?

**Comment by yeesian** [comment]
Linking https://github.com/OSGeo/gdal/blob/master/autotest/generate_sample_gpkg.py here. See also: https://github.com/OSGeo/gdal/tree/master/autotest#notes-about-availability-of-gdal-sample-and-test-data and http://download.osgeo.org/gdal/data/.

**Comment by mathieu17g** [comment]
@yeesian (cc: @Sov-trotter) this issue may be closed with PR #226 ?

ESRI Shapefile and GeoPackage layers exports to Table are somewhat tested in: 
- https://github.com/yeesian/ArchGDAL.jl/blob/8d6e1be2790a1d8d6422c28874b3ed8478e95ffc/test/test_tables.jl#L541-L594
- https://github.com/yeesian/ArchGDAL.jl/blob/8d6e1be2790a1d8d6422c28874b3ed8478e95ffc/test/test_tables.jl#L691-L714

**Comment by yeesian** [comment]
Thanks for triaging the issue @mathieu17g :)
