### ISSUE TITLE
ArchGDAL.touches error

### ISSUE THREAD

**Issue by zhangliye** [yeesian/ArchGDAL.jl#144]
When I use `ArchGDAL.touches` on two `MultiPlygon` I got the following error.

ArchGDAL.touches( g2, g1 )
ERROR: MethodError: no method matching touches(::MultiPolygon, ::MultiPolygon)
Stacktrace:
 [1] top-level scope at REPL[116]:1
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088

julia> typeof(g1), typeof(g2)
(MultiPolygon, MultiPolygon)

**Comment by yeesian** [comment]
You will need to convert your `::MultiPolygon` objects into corresponding ArchGDAL geometries.

**Comment by zhangliye** [comment]
> You will need to convert your `::MultiPolygon` objects into corresponding ArchGDAL geometries.

I am confused by the design of the GeoInterface.jl and other packages such as GeoJSON.jl and ArchGDAL.jl.  I use GeoJSON.jl to read an GeoJson file and return an GeoInterface object, such as GeoInterface.MultiPolygon which is an GeoInterface.AbstractGeometry. 

The ArchGDAL operation functions such as overlaps() and contains() all only accept ArchGDA.AbstractGeometry, rather than GeoInterfac.AbstractGeometry.  Why not GeoInterfac.AbstractGeometry input, which will make it work well with GeoJSON.jl and not need to convert the object by the user. I think this would be the value of GeoInterface.jl package.  Thanks for your great work on the Geo packages!

**Comment by yeesian** [comment]
I hear you, and you're right that the right place for that kind of interoperability happens via initiatives such as https://github.com/JuliaGeo/GeoInterfaceRFC.jl.
