### ISSUE TITLE
Functionality to get bounding box of geometry

### ISSUE THREAD

**Issue by zerefwayne** [yeesian/ArchGDAL.jl#148]
`> AG.envelope(geom)` 

`GDAL.OGREnvelope(12.445608139038143, 12.458451271057186, 41.90011215209961, 41.90755081176758)`

Instead of the OGREnvelope, it would be beneficial if I can get a POLYGON type bounding box from these coordinates.

Suggestions:

`AG.boundbox2d(geom)` which will give me a POLYGON shape

I would like to work on this feature.

**Comment by yeesian** [comment]
Yes, we haven't been very good about keeping this package hermetic and free of GDAL types, so this is a welcome contribution :)
