### ISSUE TITLE
download_verify removed on nightly

### ISSUE THREAD

**Issue by KristofferC** [yeesian/ArchGDAL.jl#154]
This package uses internals of Pkg when testing e.g.:

https://github.com/yeesian/ArchGDAL.jl/blob/9cc8713063a537f10cc2801907073f7cfd30c1c4/test/remotefiles.jl#L4-L6

These has been changed on Julia nightly. It would be good to transition these tests to use public functions (e.g. using the `download` function and then verify using the `SHA` stdlib).

**Comment by zerefwayne** [comment]
@yeesian I would like to work on this!

**Comment by visr** [comment]
That would be great! Could you make it similar to the [`download_verify`](github.com/JuliaLang/Pkg.jl/blob/5462fcaa38b0802fb507290b19ee119d5a6265b7/src/PlatformEngines.jl#L268-L352) that is used now, such that it first checks if the file exists and the SHA matches, before downloading?

**Comment by zerefwayne** [comment]
@KristofferC I was going through the Julia1.6 project board where I found that `Base.download` is being replaced by [Downloads.jl](https://github.com/JuliaLang/Downloads.jl) Should I use that package instead?

**Comment by KristofferC** [comment]
Personally, I think it is a good idea to use it but I don't maintain this package :)

**Comment by zerefwayne** [comment]
Okay thanks! @KristofferC Also, it would be helpful if you could guide me to the discussion/PR about removing `download_verify` from Pkg. I wonder if they have replaced it with something else because the function was pretty well implemented.

**Comment by KristofferC** [comment]
I don't think there is much discussion about it. There were just some small things in Pkg that changed causing the package to break which is quite common when a package uses the internals of another package. So best to just use the documented, public funtionality.
