### ISSUE TITLE
Allow gdalbuildvrt for interactive Dataset

### ISSUE THREAD

**Issue by felixcremer** [yeesian/ArchGDAL.jl#164]
For two tifs I can currently use the following code to get a vrt:
```julia
using ArchGDAL
const AG=ArchGDAL
AG.read(group[1]) do ds1
    AG.read(group[2]) do ds2
	ArchGDAL.gdalbuildvrt([ds1, ds2]) do vrt
		AG.write(vrt,tmppath)
	end
    end
end
```
Here group is a vector of two paths to .tif files. 

But I would like  to build large vrts from Sentinel-1 time series, where I am combining one hundred tifs into one vrt. 
When I change the definition of unsafe_gdalbuildvrt to also accept vectors of AbstractDatasets, I can do the following:
```julia
   tifs = AG.read.(inputpaths)
   vrt_sep = AG.unsafe_gdalbuildvrt(tifs, ["-separate"])
```
I think, that the second version is much clearer to read, especially for lots of raster files. 

I am not sure, whether I would get any problems with memory leaks due to the unsafe function.
Can we define a safe version of gdalbuildvrt for interactive datasets?

**Comment by Rapsodia86** [comment]
Try with GDAL package. 
options = GDAL.gdalbuildvrtoptionsnew(["-separate"], C_NULL)
outvrt = "U:/data/stacked.vrt"
ds_buildvrt = GDAL.gdalbuildvrt(outvrt, length(tifs), C_NULL,tifs, options, C_NULL) # 'tifs' is a vector with paths
GDAL.gdalbuildvrtoptionsfree(options)
GDAL.gdalclose(ds_buildvrt)
#and then read
outds =  ArchGDAL.readraster(outvrt)

**Comment by visr** [comment]
> When I change the definition of unsafe_gdalbuildvrt to also accept vectors of AbstractDatasets

That sounds right, a PR would be appreciated! In fact, unless I'm missing something, it looks like all the functions that still require `::Dataset` should really be `::AbstractDataset`.

> I am not sure, whether I would get any problems with memory leaks due to the unsafe function.

If you do it in a function, such that GC will get triggered when it is done, all the IDatasets will be cleaned up due to the finalizers that are defined on them, so that shouldn't be an issue.

**Comment by yeesian** [comment]
This has been fixed.
