### ISSUE TITLE
Move CI to GitHub Actions

### ISSUE THREAD

**Issue by visr** [yeesian/ArchGDAL.jl#166]
A month ago I did some automated CI maintenance in JuliaGeo repos, see https://github.com/JuliaGeo/meta/issues/15. Overall I've been quite happy switching both Travis and Appveyor over to GitHub Actions.

The most urgent one is Travis. that is now on https://travis-ci.org/github/yeesian/ArchGDAL.jl with a banner that you have to move to travis.com within weeks. And from what I've seen the open source credits for travis.com are hard to come by.

**Comment by yeesian** [comment]
Thanks for alerting me to this!
