### ISSUE TITLE
Guess output file driver

### ISSUE THREAD

**Issue by rafaqz** [yeesian/ArchGDAL.jl#173]
Currently we have `identifydriver`, but this is for identifying an existing file. We could also guess the driver based on the file extension, for a file we intend to write.Similar functionality been merged for rasterio, see:

https://github.com/mapbox/rasterio/pull/2008
https://github.com/Toblerity/Fiona/pull/948/files

Any thoughts? I think it's better to have this here than in GeoData.jl, I'll put together a PR if people are interested.

Edit (although the rasterio license seems pretty vague for actually reading/copying these):

In rasterio, most of the action is here - where all drivers have their extensions collated from GDAL:
https://github.com/mapbox/rasterio/blob/99511e4069feec4db91374243b7edc382b620b9d/rasterio/_base.pyx#L120

We could have a similar method, but just `driver_extensions`, returning a `Dict` of extensions and their drivers.

They then have `driver_from_extension` function:
https://github.com/mapbox/rasterio/blob/d7b2dd3ae64c55978e265fa9230732e88b1dc9ae/rasterio/drivers.py#L37

With some fallbacks for < GDAL 2.0. Which we probably don't have to worry about.

**Comment by yeesian** [comment]
Sure yeah that sounds like a useful utility to have :)

**Comment by evetion** [comment]
Fore sure useful, I've hit this myself as well in https://github.com/evetion/GeoArrays.jl/blob/70756bae40dee614ed88dc194cbea9382fb76e7c/src/utils.jl#L7 and https://github.com/evetion/GeoDataFrames.jl/blob/0c3b2c6ec1b25ba53c0ffbb208b1af5ae166817c/src/io.jl#L28
