### ISSUE TITLE
nodatavalue type may be different to array eltype

### ISSUE THREAD

**Issue by rafaqz** [yeesian/ArchGDAL.jl#188]
I'm not sure if this is a GDAL problem, or a problem in the files themselves. But it is possible to get a `Float64` nodata value from `AG.getnodatavalue` with a `Float32` band. The problem with this is they may not be equal due to floating point representations.

**Comment by visr** [comment]
Hmm yeah the GDAL API just always returns a Float64 here, so it is probable best to always use `isapprox` on the result.

https://github.com/JuliaGeo/GDAL.jl/blob/d44dc737ec16a60d1edb81bb71e0cb5f0666f165/src/gdal_h.jl#L1875-L1883

**Comment by rafaqz** [comment]
`convert(eltype(band), nodatavalue)` is another option. But that can also just live in GeoData.jl

**Comment by visr** [comment]
Hmm yeah, that could fail though, since technically you can have an Int32 band with a nodata value of say 1.23. And is this going to guarantee that you get the same floating point representation?

**Comment by rafaqz** [comment]
Mostly it will fix the floating point differences in my experience. It could also be used just on Floating point and not on Int, the main problem seems to be `Float32` not reprsenting things accurately... Where `Int` is _very_ good at representing integers accurately ;)

In GeoData.jl its available to users as `missingval(A)`, and it would be nice if it worked in arbitrary scripting uses without `isapprox`

**Comment by visr** [comment]
Yeah I understand it is not very convenient. I'll leave it to Yeesian to decide if this would change semantics, ref https://github.com/yeesian/ArchGDAL.jl/pull/176#issuecomment-792230666.

**Comment by rafaqz** [comment]
Maybe it should be fixed in GDAL... it's pretty weird really.

**Comment by Rapsodia86** [comment]
I will follow here the topic of nodatavalue. Is there an option to update/assign new value to nodata? Or the only way is to read to array, replace value and then while writing to raster assing nodata using:  ArchGDAL.setnodatavalue!(band, -9999) ?

**Comment by yeesian** [comment]
Yeah I agree with  https://github.com/yeesian/ArchGDAL.jl/issues/188#issuecomment-831767137 and https://github.com/yeesian/ArchGDAL.jl/issues/188#issuecomment-831821048 -- I think the best place for fixing it will be in https://github.com/OSGeo/gdal

**Comment by rafaqz** [comment]
Fixed over at gdal: https://github.com/OSGeo/gdal/pull/3794
