### ISSUE TITLE
Enable more tests (finish unfinished tests)

### ISSUE THREAD

**Issue by evetion** [yeesian/ArchGDAL.jl#19]
In several test files, before and after statements are printed. These files often contain no functional tests and are thus only partly finished:

```julia
AG.importEPSG(26912) do spatialref
        println("before (Proj4): $(AG.toPROJ4(spatialref))")
        println("before (WKT): $(AG.toWKT(spatialref))")
        AG.morphtoESRI!(spatialref)
        println("after (Proj4): $(AG.toPROJ4(spatialref))")
        println("after: $(AG.toWKT(spatialref))")
end
```

We should finish these tests, they can be used at the least for regression testing.

**Comment by yeesian** [comment]
Might you be able to have a crack at this one, so I have some time to work on the documentation?

**Comment by evetion** [comment]
Sure, I'll take a look.
