### ISSUE TITLE
Updating/editing nodata

### ISSUE THREAD

**Issue by Rapsodia86** [yeesian/ArchGDAL.jl#197]
I do have a question about nodata value. Is there an option to update/assign new value to nodata? Or the only way is to read to array, replace the value and then while writing to raster assign nodata using: ArchGDAL.setnodatavalue!(band, -9999) ?

**Comment by evetion** [comment]
There are multiple ways to specify nodata values in rasters in GDAL. What you propose could be done by updating a nodata mask, without touching the data values directly. However, these masks are rare, most of the datasets have a simple nodata value set and one does indeed need to replace the values directly.

**Comment by Rapsodia86** [comment]
Ok, thank you very much for the clarification!
