### ISSUE TITLE
Check if conversion is needed for proxy Enums

### ISSUE THREAD

**Issue by evetion** [yeesian/ArchGDAL.jl#213]
In v0.7, most of the enums from GDAL have their ArchGDAL proxy. The docs explicitly state to use convert, i.e.
`convert(GDAL.OGRFieldType, ArchGDAL.OFTInteger)` to get the GDAL equivalent.

However, this is not done in the code, for example: https://github.com/yeesian/ArchGDAL.jl/blob/898cac6418db5be8ee4aad2292131b2c3e91fc84/src/ogr/fielddefn.jl#L8.

I can't see the exact `OGRFieldType` import, nor am I familiar with the cases where these proxy enums could diverge, but it seems like a possible place for buggy behaviour.

**Comment by yeesian** [comment]
Users of this should not have to use any enums from GDAL.jl and should be using the API from ArchGDAL.jl. In the code snippet in https://github.com/yeesian/ArchGDAL.jl/issues/213#issue-934810038, the way to know what can be used for `OGRFieldType` can be looked up in the REPL:

```julia
julia> ArchGDAL.OGRFieldType
Enum ArchGDAL.OGRFieldType:
OFTInteger = 0
OFTIntegerList = 1
OFTReal = 2
OFTRealList = 3
OFTString = 4
OFTStringList = 5
OFTWideString = 6
OFTWideStringList = 7
OFTBinary = 8
OFTDate = 9
OFTTime = 10
OFTDateTime = 11
OFTInteger64 = 12
OFTInteger64List = 13
OFTMaxType = 14
```

**Comment by evetion** [comment]
@yeesian This is not about user behaviour, this is about whether we need to do the conversion ourselves in the place I linked to. It seems we create the GDAL field with an ArchGDAL enum.

**Comment by yeesian** [comment]
Oh, you shouldn't be doing the conversion yourself in the place you linked to. I.e. it should be called like `ArchGDAL.unsafe_createfielddefn("field name", ArchGDAL.OFTStringList)`. The conversions will happen under-the-hood via [this code](https://github.com/yeesian/ArchGDAL.jl/blob/f98a7cdce3482691ab526e3fbbf796d23aec35ed/src/types.jl#L238-L511).
