### ISSUE TITLE
Handle non-bijective data-type conversions more robustly

### ISSUE THREAD

**Issue by yeesian** [yeesian/ArchGDAL.jl#232]
Given that we're using dictionaries for the code to convert between data types, there's no good way of [asserting "default type comes last" for mappings that are not bijective](https://github.com/yeesian/ArchGDAL.jl/blob/f4406a55c5e2d42e0617e5e686d87f71d376d4be/src/types.jl#L305-L310).

Opening this ticket to
* Include it in the docstring for the `convert` macro.
* Add unit tests for them.
* Rewrite the implementation to [enforce it by construction](https://discourse.julialang.org/t/initialising-a-dictionary-with-duplicate-keys/2290/2).

**Comment by yeesian** [comment]
Looks like it was discussed in e.g. https://discourse.julialang.org/t/initialising-a-dictionary-with-duplicate-keys/2290 in the past.

**Comment by mathieu17g** [comment]
> Looks like it was discussed in e.g. https://discourse.julialang.org/t/initialising-a-dictionary-with-duplicate-keys/2290 in the past.

I will give it a try
