### ISSUE TITLE
`@convert`macro does not handle well conversion from `ImageCore.Normed` types to `ArchGDAL.GDALDataType`

### ISSUE THREAD

**Issue by mathieu17g** [yeesian/ArchGDAL.jl#235]
**Edit:** with master version up to commit 72d58c7

`@convert`macro does not handle well conversion from `ImageCore.Normed` types to `ArchGDAL.GDALDataType`
Therefore the `convert(::Type{ArchGDAL.GDALDataType}, x::ImageCore.Normed)` function does not work does not work 

```julia
julia> using ArchGDAL

julia> using ImageCore

julia> convert(ArchGDAL.GDALDataType, ImageCore.N0f8(0.5))
ERROR: MethodError: Cannot `convert` an object of type 
  Type{N0f8} to an object of type 
  Normed
Closest candidates are:
  convert(::Type{T}, ::Gray24) where T<:Real at /Users/Mathieu/.julia/packages/ColorTypes/7OlxI/src/conversions.jl:114
  convert(::Type{T}, ::Gray) where T<:Real at /Users/Mathieu/.julia/packages/ColorTypes/7OlxI/src/conversions.jl:113
  convert(::Type{Normed}, ::ArchGDAL.GDALDataType) at /Users/Mathieu/.julia/packages/ArchGDAL/tW7AO/src/utils.jl:32
  ...
Stacktrace:
 [1] cvt1
   @ ./essentials.jl:322 [inlined]
 [2] ntuple
   @ ./ntuple.jl:49 [inlined]
 [3] convert(#unused#::Type{Tuple{Normed, ArchGDAL.GDALDataType}}, x::Tuple{DataType, ArchGDAL.GDALDataType})
   @ Base ./essentials.jl:323
 [4] setindex!(A::Vector{Tuple{Normed, ArchGDAL.GDALDataType}}, x::Tuple{DataType, ArchGDAL.GDALDataType}, i1::Int64)
   @ Base ./array.jl:839
 [5] getindex
   @ ./array.jl:394 [inlined]
 [6] convert(#unused#::Type{ArchGDAL.GDALDataType}, ft::N0f8)
   @ ArchGDAL ~/.julia/packages/ArchGDAL/tW7AO/src/utils.jl:40
 [7] top-level scope
   @ REPL[2]:1

```

It may be due to `N0f8`, `N0f16` and `N0f32` particular definition in FixedPointNumbers.jl

**Comment by mathieu17g** [comment]
Sorry, I made a mistake in the errored call to `convert`.
The correct usage is `convert(ArchGDAL.GDALDataType, ImageCore.N0f8)`
But the it is still errored
```julia
julia> convert(ArchGDAL.GDALDataType, N0f8)
ERROR: MethodError: Cannot `convert` an object of type Type{N0f8} to an object of type ArchGDAL.GDALDataType
Closest candidates are:
  convert(::Type{ArchGDAL.GDALDataType}, ::Type{ComplexF64}) at /Users/Mathieu/OneDrive - Altice Campus SFR/code_julia/radio_sites_near_motorways/dev/ArchGDAL/src/utils.jl:89
  convert(::Type{ArchGDAL.GDALDataType}, ::Type{ComplexF32}) at /Users/Mathieu/OneDrive - Altice Campus SFR/code_julia/radio_sites_near_motorways/dev/ArchGDAL/src/utils.jl:89
  convert(::Type{ArchGDAL.GDALDataType}, ::Type{Float64}) at /Users/Mathieu/OneDrive - Altice Campus SFR/code_julia/radio_sites_near_motorways/dev/ArchGDAL/src/utils.jl:89
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```
By changing Normed` to `DataType` in the call to `@convert` marcro
```julia
@convert(
    GDALDataType::DataType,
    GDT_Byte::ImageCore.N0f8,
    GDT_UInt16::ImageCore.N0f16,
    GDT_UInt32::ImageCore.N0f32,
)
```
You get the following result
```julia
julia> using ArchGDAL

julia> using ImageCore

julia> convert(ArchGDAL.GDALDataType, N0f8)
GDT_Byte::GDALDataType = 1

julia> convert(DataType, ArchGDAL.GDT_Byte)
UInt8
```

@yeesian @visr is it OK for you ? 
I'm not familiar with usage of `Normed` types in ArchGDAL. Do you see any consequence of not being able to convert an `ArchGDAL.GDALDataType` to a `Normed` type but only to its related primitive type ? All the test are OK

**Comment by yeesian** [comment]
I think this is still working as intended and isn't a bug. The conversion code was introduced to facilitate [working with images](https://yeesian.com/ArchGDAL.jl/dev/images/) ([corresponding code](https://github.com/yeesian/ArchGDAL.jl/blob/f98a7cdce3482691ab526e3fbbf796d23aec35ed/src/raster/images.jl)): we only support Gray and RGB right now. 

It might be nice to have more general support for https://github.com/JuliaGraphics/ColorTypes.jl, but It's unclear to me whether we need full support for all ImageCore.Normed types (although it wouldn't hurt to have it).
