### ISSUE TITLE
TODO for registration

### ISSUE THREAD

**Issue by evetion** [yeesian/ArchGDAL.jl#24]
I would really like for this package to be registered. What do you think that needs to be done for this? I've created the same issue for visr/GDAL.jl#44 as this package depends heavily on it.

- [x] #19 Finish tests
- [x] #10 Move large test data
- [ ] ...?

**Comment by yeesian** [comment]
If we
- register GDAL.jl (https://github.com/visr/GDAL.jl/issues/44)
- clear up #10

Then I'll be happy enough to register this package.

**Comment by evetion** [comment]
Looks we can register? 👍

**Comment by visr** [comment]
Fixing #37 would be very breaking. Do you think it is better to fix it first?

**Comment by yeesian** [comment]
Yeah I agree. I have something in https://github.com/yeesian/ArchGDAL.jl/commit/88b62359a3df05ad980d26c858f289a2c4973c89, but haven't had the time since to see it through.

**Comment by yeesian** [comment]
I'll be okay with moving ArchGDAL.jl over to julia 0.7 minimum too.

> Do you intend that only the imread functions permute their dims? Or any kind of array that is read from GDAL?

I don't use the raster side of GDAL to know what'll make more sense to people. Do you feel we should permute the arrays as well? Might there be cases where people prefer for it to not be permuted?

**Comment by visr** [comment]
I just pushed a `juliacon` branch for julia 0.7. Only the iterators are not yet migrated.

> Might there be cases where people prefer for it to not be permuted?
Not that I can think of. I think permuting all the rasters makes sense. Not sure how much more complicated it is though.

**Comment by yeesian** [comment]
Based on the [discussion](https://github.com/yeesian/ArchGDAL.jl/issues/37#issuecomment-426532618) we've had, I think this package is finally ready for registration.

**Comment by visr** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/18609
