### ISSUE TITLE
boundingbox exchanged coordinates

### ISSUE THREAD

**Issue by ErickChacon** [yeesian/ArchGDAL.jl#253]
Is it desired that the boundingbox function swaps the coordinates X and Y?

```julia
using ArchGDAL; const AG = ArchGDAL
using Plots
poly = ArchGDAL.createpolygon([(5.,0.), (0.,1.), (5.,1.)])
box = AG.boundingbox(poly)
plot(poly, label = "geom")
plot!(box, label = "boundingbox", alpha = 0.4, legend = true)
```
![boundingbox](https://user-images.githubusercontent.com/7862458/137572766-a0841066-03d8-4aac-b588-a49517b262f4.png)

**Comment by yeesian** [comment]
Thanks for the report!
