### ISSUE TITLE
Windows x64 build failing

### ISSUE THREAD

**Issue by evetion** [yeesian/ArchGDAL.jl#27]
on:
`Reproject a Geometry: Error During Test
  Got an exception of type GDAL.GDALError outside of a @test
  GDALError (Failure, code 4):
  	Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.`
([source](https://ci.appveyor.com/project/NgYeeSian/archgdal-jl/build/1.0.140/job/fhn70yh81xj9r15a))
So this one isn't related to visr/GDAL.jl#42, as the x64 build works over there.

**Comment by visr** [comment]
Hmm I don't see this error in your link? Is it still an issue?
I'd expect ArchGDAL to indirectly also make use of [GDAL setting GDAL_DATA](https://github.com/visr/GDAL.jl/blob/480f42b67a692e389d3064f1744d820a7ff194e9/src/GDAL.jl#L113).

**Comment by evetion** [comment]
Sorry, linked to the 32bit build. This is the 64bit [build](https://ci.appveyor.com/project/NgYeeSian/archgdal-jl/build/1.0.140/job/fhn70yh81xj9r15a).

**Comment by evetion** [comment]
This should be fixed by #48. Closing.
