### ISSUE TITLE
Remove DiskArrays 0.2.4 compat entry from Project.toml

### ISSUE THREAD

**Issue by maxfreu** [yeesian/ArchGDAL.jl#277]
It seems like version 0.2.4 is not compatible with the latest ArchGDAL version. Cross posting from [here](https://github.com/rafaqz/Rasters.jl/issues/244)

>Looks like ArchGDAL has done a minor version bump of DiskArrays.jl, and not removed compat for versions before 0.3. That bug is entirely between ArchGDAL and version 0.2.4 of DiskArrays, which is no longer supported but is still included in the ArchGDAL Project.toml.
Please make an issue over there to remove compat with disk arrays 0.2.4, and to remove the current ArchGDAL version from the julia registry.

**Comment by rafaqz** [comment]
Yanked: https://github.com/JuliaRegistries/General/pull/53421
