### ISSUE TITLE
Failing tests on 1.9

### ISSUE THREAD

**Issue by evetion** [yeesian/ArchGDAL.jl#285]
As seen in master and in recent PRs (#284), nightly fails with

`MethodError: no method matching regenerateoverviews!(::ArchGDAL.IRasterBand{UInt8}, ::Vector{Matrix{UInt8}})`
https://github.com/yeesian/ArchGDAL.jl/runs/5513853907?check_suite_focus=true#step%3A6%3A165=

**Comment by yeesian** [comment]
Thank you for filing this; I looked at the code and it seems that everything's working as-intended, but please correct me if I'm wrong! 

In the meantime, let me doublecheck that failure on nightlies are not a blocker for merging PRs

**Comment by evetion** [comment]
Ok, from what I can see, in the failing function `regenerateoverviews!(::T, ::Vector{<:ArchGDAL.AbstractRasterBand})` Julia normally dispatches fine on `Vector{<:ArchGDAL.AbstractRasterBand}`. In Julia 1.9 it doesn't and walks all the way up its supertypes to `Matrix` as `ArchGDAL.AbstractRasterBand <: AbstractDiskArray{T,2} <: <: AbstractArray{T,N}`.

Will file an upstream bug report.

**Comment by yeesian** [comment]
I really appreciate your investigation and follow-up in https://github.com/JuliaLang/julia/issues/44821. The lack of stability in the common type for vectors seems slightly concerning. Should I consider setting up a system of promotion rules defined for the types in this package?

**Comment by evetion** [comment]
It seems wise to add promotion rules indeed, but only for the (probably small amount) of cases where it's needed. In the test we triggered this by mixing both `RasterBand` and `IRasterBand`, the same is probably needed for Geometry, but I don't know more cases. I also don't expect a user to quickly mix these, as the public interface mostly works with the `I` variants.
