### ISSUE TITLE
Transfer ArchGDAL.jl to JuliaGeo

### ISSUE THREAD

**Issue by ViralBShah** [yeesian/ArchGDAL.jl#292]
@yeesian Thanks for developing ArchGDAL.jl. I have enjoyed the talks you gave at JuliaCon, and also have seen my collaborators use it in the Circuitscape ecosystem.

It is great to see it grow and also receive contributions from many people. Given that it is increasingly becoming a core package in the JuliaGeo ecosystem, would it be ok with you to transfer it to the JuliaGeo organization (with you naturally having full admin control over the package in JuliaGeo)?

**Comment by yeesian** [comment]
Thanks for opening this ticket. I prefer that the right level of support goes to https://github.com/JuliaGeo/GDAL.jl first, but I'm open to the idea.

**Comment by ViralBShah** [comment]
Agree. It was just a thought - Closing for now and can always reopen when the time is right in the future.

**Comment by ViralBShah** [comment]
My mental model is that ArchGDAL.jl is a level of abstraction on GDAL.jl (which I believe is a wrapper around libgdal)? Is that the right mental model? 

In our Circuitscape project ([Omniscape.jl](https://github.com/Circuitscape/Omniscape.jl)), I noticed that we moved from using GDAL.jl to ArchGDAL.jl and hence I thought they would belong to the same org and they would have the same group of people contributing.

I would love to update my mental model if I don't have it right.

**Comment by yeesian** [comment]
I think my idea of a northstar is if we can auto-generate the code for GDAL.jl from Clang.jl with systematic rewriting logic like https://github.com/JuliaGeo/GDAL.jl/blob/2366302ee66a189aed673b03dd7da2a9589092e3/gen/generator.jl#L67-L134 such that it achieves a similar level of user experience as this package, while minimizing long-term toil for maintainers to keep it up-to-date with GDAL.

This package was created for me to try to "front-run" and see what the user experience for such rules could be like, and incur the "costs" of figuring it out (through having conversations and resolving bugs and inconsistencies) without unduly burdening the JuliaGeo organization which has a really wide surface area of C APIs to cover, and no real funding/support beyond voluntary contributions.

**Comment by ViralBShah** [comment]
This background is very helpful, thank you!

**Comment by ViralBShah** [comment]
@logankilpatrick Note that this could be a potential future NF small grant or JSOC.
