### ISSUE TITLE
Can't create geometry with non-Float64 vectors

### ISSUE THREAD

**Issue by evetion** [yeesian/ArchGDAL.jl#304]
Encountered in #290, with creation of geometry from `GeoInterface.coordinates(geom)`, which are nested `Vector`s of `<:Real`.

While you can create points with Integers:

```julia
julia> import ArchGDAL as AG
julia> AG.createpoint([1,2])
Geometry: POINT (1 2)
```

You cannot do so with more complex geometries, even with LineString:
```julia
julia> AG.createlinestring([[1,2],[1,2]])
ERROR: MethodError: no method matching createlinestring(::Vector{Vector{Int64}})
```

Not even with other Float types:
```julia
julia> AG.createlinestring([Float32.([1,2]),Float32.([1,2])])
ERROR: MethodError: no method matching createlinestring(::Vector{Vector{Float32}})
```

**Comment by rafaqz** [comment]
Maybe this is an unnessesary limitation, swapping to `<:Real` seems to work fine. 


Seeing its defined in multiple places, something like this could help:
```julia
const _POINTTYPES = Vector{<:Tuple{<:Real,<:Real}}}},
                Vector{<:Tuple{<:Real,<:Real,<:Real}}}},
                Vector{<:Vector{<:Real}}}}
```

**Comment by yeesian** [comment]
I don't think it's due to any fundamental GDAL reason, and is probably me not being sufficiently clever to think about how to write it to cover all cases.

**Comment by rafaqz** [comment]
I'll PR when I have time, its an easy fix.
