### ISSUE TITLE
Clarify geometry equality

### ISSUE THREAD

**Issue by rafaqz** [yeesian/ArchGDAL.jl#306]
This should return `true`?

```julia
julia> ArchGDAL.createpoint(1.0, 2.0) == ArchGDAL.createpoint(1.0, 2.0)
false
```

And `===` should be `false` ?

Currently Base is just comparing if the pointers to the gdal points are the same:
```julia
julia> @which ArchGDAL.createpoint(1.0, 2.0) == ArchGDAL.createpoint(1.0, 2.0)
==(x, y) in Base at Base.jl:119
```

We could add a `==` method to compare the contents of the pointers.

**Comment by visr** [comment]
I think it would indeed be nice if `==` would return true there.
It looks like we could just forward `Base.==` to the `ArchGDAL.equals` method (`ogr_g_equals`)? `GeoInterface.equals` also forwards there.
