### ISSUE TITLE
Help with Grib files

### ISSUE THREAD

**Issue by zahachtah** [yeesian/ArchGDAL.jl#31]
Hi, I have installed ArchGdal and Gdal.jl successfully and all tests pass.

I started with 

```
using ArchGDAL

const AG = ArchGDAL

import base.read

function read(f, filename)
                  return AG.registerdrivers() do
                      AG.read(filename) do dataset
                          f(dataset)
              end end end
```
I then have a file directory ```file``` and do:
```
read(file*"/interim_vswl1_12_N80.grib") do dataset
                  print(dataset)
              end;
CPLDestroyMutex: Error = 16 (Resource busy)
CPLDestroyMutex: Error = 16 (Resource busy)
ERROR: GDALError (Failure, code 4):
    /Users/jonnorberg/Documents/ecmwf/rawData/interim_vswl1_12_N80.grib is a grib file, but no raster dataset was successfully identified.
```

This is probably due to me not having used gdal at all before so I would just like to ask if there is anything obvious I can do to extract the data.

Any hints is appreciated!

**Comment by yeesian** [comment]
You can try running `gdalinfo --debug` on the grib file (based on https://stackoverflow.com/questions/13862422/can-r-read-grib-filewhen-it-is-not-raster-and-convert-it-to-ascii-file)

**Comment by zahachtah** [comment]
I found this on the ecmwf homepage:

the GDAL library, with limited support for coordinate systems, georeferencing and metadata. In particular irregular (non-cartesian) coordinate systems might not be decoded correctly.

In fact these are all irregular (non-cartesian) coordinate systems as it is direct output from computation optimised calculations. I will have to stick to my old and clumsy way of extracting these data :-)

thanks for input

**Comment by yeesian** [comment]
No worries!
