### ISSUE TITLE
Why does `createlinearring` create a wkbLineString

### ISSUE THREAD

**Issue by rafaqz** [yeesian/ArchGDAL.jl#314]
See: https://github.com/yeesian/ArchGDAL.jl/blob/master/test/test_geometry.jl#L292

I'm trying to fix type stability of geometry creation for performance (some large gains from small changes) but `createlinearring` is a strange wart to special-case.

Why does it return a `wkbLineString`? as the comment says, it seems very odd.

**Comment by rafaqz** [comment]
Yeah seems like something like that. So the question is really in what cases does GDAL actually return `wkbLinearRing` form `ogr_g_getgeometrytype`, if ever?

Hard to make things type stable without knowing that. This is a pretty commmon path to - getting rings from a polygon - so it would be good to make it faster.

**Comment by visr** [comment]
It seems never, based on this comment:
```cpp
wkbLinearRing = 101,    /**< non-standard, just for createGeometry() */
```

From https://github.com/OSGeo/gdal/blob/v3.5.1/ogr/ogr_core.h#L401

**Comment by rafaqz** [comment]
Ok great. We can lock in `wkbLineString` as the type parameter.
