### ISSUE TITLE
ArchGDAL testing returns an error

### ISSUE THREAD

**Issue by psavary3** [yeesian/ArchGDAL.jl#331]
I am using Julia 1.4.1 on Ubuntu 20.04.5 LTS. 
When I test ArchGDAL (with 'using Pkg; Pkg.test("ArchGDAL"), I get an error that seems to be due to a libc.so.6 error. I get the same error when testing GDAL. This lib is in my system, in the folder "/usr/lib/i386-linux-gnu".
I use GDAL_jll v300.201.100+1 and gdal v1.2.6. 
Is there any solution to that problem?

Here is the source of the error:
"signal (6): Abandon
in expression starting at /home/paul/.julia/packages/GDAL/LljeA/test/tutorial_raster.jl:21
gsignal at /usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (unknown line)"

Thanks
(I am a very beginner at Julia coding)

**Comment by evetion** [comment]
Could you test with a more recent Julia version? Julia only supports 1.6 and 1.8 currently, with 1.6 being the Long Term Support (LTS) version and 1.8 the most recent stable one.

**Comment by psavary3** [comment]
Actually, the problem came from the Julia path in Visual Studio Code. VSC used Julia 1.4 although I had installed a more recent one. Changing this path for the one pointing to Julia 1.8 and reinstalling packages solved the problem.
A very beginner error...
Thank you for your help
