### ISSUE TITLE
GDAL 3.6.0

### ISSUE THREAD

**Issue by visr** [yeesian/ArchGDAL.jl#345]
See https://github.com/JuliaGeo/GDAL.jl/pull/143.
I saw locally that 9 ArchGDAL tests were failing using that branch, but from a quick glance nothing serious. Though let us know if you want us to hold off merging and tagging that PR.

**Comment by yeesian** [comment]
> I saw locally that 9 ArchGDAL tests were failing using that branch, but from a quick glance nothing serious. Though let us know if you want us to hold off merging and tagging that PR.

Should we upperbound the dependency on GDAL here? In the [NEWS](https://github.com/OSGeo/gdal/blob/b77481ccf9f84a708fd37a13a7e0a3384fdf1622/NEWS.md?plain=1#L124-L125), it's written that

```
Breaking changes: Remove use of compatibility wrappers _GetProjectionRef / _GetGCPProjection / _SetProjection / _SetGCPs (#6186)
```

So I think this package will need to be updated to remain compatible with GDAL 3.6+.

**Comment by evetion** [comment]
> Should we upperbound the dependency on GDAL here? In the [NEWS](https://github.com/OSGeo/gdal/blob/b77481ccf9f84a708fd37a13a7e0a3384fdf1622/NEWS.md?plain=1#L124-L125), it's written that

I think we must. We've seen multiple times that upstream releases (not only GDAL, also PROJ for example) introduces changes that break tests or actual production code. You can't prevent that with pinning ArchGDAL.

**Comment by evetion** [comment]
> The getfield related failures, I don't know why they are failing on the new GDAL.

That would be the bugfix:
 - OGRFeature::FillUnsetWithDefault(): do not set driver-specific default values on unset numeric fields
