### ISSUE TITLE
Failure during testing on Windows x64: PROJ.4 library (libproj-9.dll) missing

### ISSUE THREAD

**Issue by niclasmattsson** [yeesian/ArchGDAL.jl#35]
I managed to install, build and test GDAL without errors. However `Pkg.test("ArchGDAL")` fails with the following error:

```
Test Summary:                 |
Force polygon to multipolygon | No tests
Method 1
Reproject a Geometry: Error During Test
  Got an exception of type GDAL.GDALError outside of a @test
  GDALError (Failure, code 6):
        Unable to load PROJ.4 library (libproj-9.dll), creation of OGRCoordinateTransformation failed.
```

Earlier during testing I got another error that `gcs.csv` couldn't be found, but I fixed that by setting the `GDAL_DATA` environment variable to `C:\Users\niclas\.julia\v0.6\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\share`. Not very obvious, thank goodness for search. :) But the library `libproj-9.dll` appears to be nowhere on my system. Do I need to do a manual install of GDAL?

**Comment by yeesian** [comment]
Yeah, manually installing and linking to GDAL will be the most straightforward way for now.

@visr is working on a better way of building and distributing GDAL binaries over at https://github.com/visr/GDALBuilder, but we're not there yet.

**Comment by visr** [comment]
Yeah, for now it is probably easiest to:
- delete GDAL.jl\deps\deps.jl
- install OSGeo4W64 with full gdal+proj
- in your  home dir, make a `.juliarc.jl` with `push!(Libdl.DL_LOAD_PATH, "c:/OSGeo4W64/bin/")` such that julia can find the dll's there
- run `Pkg.build("GDAL")`, and see in the deps.jl if it picks up the  OSGeo4W one

**Comment by niclasmattsson** [comment]
Thanks, but I still get the same error after manually installing GDAL. I followed [these installation instructions](https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows) and grabbed [GDAL 2.2.3 from GISinternals](http://www.gisinternals.com/release.php). GDAL seems to be working but I still have no `libproj*.dll` files on my system.

When I googled "windows proj4" in hope of finding the missing DLL I found several references to OSGeo4W, which also includes GDAL. So I tried installing that too but it didn't help. Any other ideas?

**Comment by niclasmattsson** [comment]
When I followed the steps @visr listed the projection test passed. I checked in deps.jl and apparently it used the main GDAL install, which means I could remove OSGeo4W from my system. But as you said, the change to build.jl was needed to avoid using the WinRPM version.

FYI I got another error during test cleanup:
```
Test Summary:  |
Get Projection | No tests
ERROR: LoadError: could not spawn `rm 'C:\Users\niclas\.julia\v0.6\ArchGDAL\test\data/A.tif'`: no such file or directory (ENOENT)
```

I fixed this one myself by changing ``run(`rm $currfile`)`` in runtests.jl to `rm(currfile)`. After that all tests passed.

Thanks for the help! I'm going to start playing around with the packages now, so I suspect this won't be the last you hear of me. :)

**Comment by visr** [comment]
Great that it worked.

Your change in runtests.jl seems like an improvement, since `rm` doesn't exist under CMD in Windows. We'd appreciate if you could click the pencil/edit button on [runtests.jl](https://github.com/yeesian/ArchGDAL.jl/blob/master/test/runtests.jl) and fix it directly, so we all benefit :)

**Comment by visr** [comment]
Yep, the PR is needed. Otherwise you only edit it in you [local fork](https://github.com/niclasmattsson/ArchGDAL.jl/tree/patch-1), and the PR is the request to pull in your local change here as well. Thanks!

**Comment by visr** [comment]
The GDAL build is now based on BinaryBuilder. Seems we can close this issue. Do let us know if you are still having issues.
