### ISSUE TITLE
transposed rasters

### ISSUE THREAD

**Issue by visr** [yeesian/ArchGDAL.jl#37]
If a complete band is read into an array, the x and y dimensions are flipped:
```julia
using ArchGDAL

filepath = "dem.tif"

arr = ArchGDAL.registerdrivers() do
    ArchGDAL.read(filepath) do dataset
        ArchGDAL.read(dataset, 1)
    end
end
summary(arr) # => 97×33 Array{UInt8,2}

run(`gdalinfo $filepath`)
⋮
Size is 97, 33 # this is ncol, nrow
Band 1 Block=97x1 Type=Byte, ColorInterp=Undefined # blocks are single rows
⋮
```

This is because GDAL is row-based and Julia column-based.
Some options regarding this:
- Keep as is, warn in the docs that users must take this into account
- Call `permutedims` ([docs](https://docs.julialang.org/en/latest/base/arrays/#Base.permutedims)) before returning the array. Makes a copy of the whole dataset.
- Return a `PermutedDimsArray` ([docs](https://docs.julialang.org/en/latest/base/arrays/#Base.PermutedDimsArrays.PermutedDimsArray)). This does not create a copy, but a permuted view.

I haven't really worked with `PermutedDimsArray` yet, but to me it seems like the best choice right now. Thoughts?

**Comment by yeesian** [comment]
I'm also in preference of having the third option as the default. Should we
- rename `read` to `read_colbase`
- add `read_rowbase(...) = PermutedDimsArray(read_colbase(...), (2,1))`
- add the alias `read = read_rowbase`

?

**Comment by visr** [comment]
I'm not sure whether it is worth the extra code/maintenance/complexity to have a `read_rowbase` and `read_colbase` distinction.

Other options are `read` defaults to `PermutedDimsArray` and a keyword option to get `permutedims`, or the other way around. I just saw https://github.com/JuliaIO/ImageMagick.jl/pull/103, where they opted for the latter.

But for geospatial rasters small arrays may not be as common? And if we want to write the results back to GDAL again, there is no need to copy a second time if we use `PermutedDimsArray`.

**Comment by yeesian** [comment]
Let's just go with `PermutedDimsArray` for now then. Can always add in more options later when there are requests for it.

**Comment by yeesian** [comment]
Sorry I'm a little overwhelmed by work at the moment. But I'll be happy to take PRs

**Comment by yeesian** [comment]
> Was just the result of a little private discussion we had about the pros and cons of doing this :)

Anything we should note? Might this be related to [the discussion on AbstractRasters in GeoInterface](https://github.com/JuliaGeo/GeoInterface.jl/issues/16#issuecomment-420629760)?

**Comment by visr** [comment]
No I don't think it directly relates to that discussion. See also https://github.com/yeesian/ArchGDAL.jl/pull/57#issuecomment-425055502

**Comment by evetion** [comment]
After a discussion in #57, @yeesian, summarizing my viewpoint:

> That sounds reasonable to me. To state what I understand of your comment: either the user
>
>    (a) deals with the "raw data" (through the current read()/write() methods) and does what they want with it (we can document permuteddims view for them), or
>    (b) views it as an "image" object similar to how it might be dealt with in the JuliaImages organization (through ongoing work in the images branch to support imread()/imwrite()). This handles issues like permuting the array, normalizing the values, and identifying the color channels.
>
> Being stuck in the middle ground between (a) and (b) sounds like an easy way to cause confusion for users.

I closed the PR. I would opt for a new PR, implementing the documentation in discussed in (a) and leave it at that. 

We can leave this issue open for a week or two(? @visr), so others can state their views.

**Comment by evetion** [comment]
Added documentation in #60

**Comment by yeesian** [comment]
Closed by #60

**Comment by AmebaBrain** [comment]
@evetion you closed this issue with comment below in `rasters.md`
> The array returned by `read` has `(rows, cols, bands)` dimensions. 

But actual return size seems to be still `(col, row)`

```
import ArchGDAL
const AG = ArchGDAL

filepath = "../data/geo/world.tif"

AG.registerdrivers() do
    AG.read(filepath) do dataset

        band = AG.getband(dataset, 1)
        println( "height (rows): " * repr(AG.height(band)))
        println("width (cols): " * repr(AG.width(band)))

        # returned shape is (col, row) and not (rows, cols, bands) as stated in docs
        data = AG.read(band)
        println("data size by reading band: " * repr(size(data)))

        data = AG.read(dataset, 1)
        println("data size by reading dataset: " * repr(size(data)))
    end
end
```
output
--------
height (rows): 1024
width (cols): 2048
data size by reading band: (2048, 1024)
data size by reading dataset: (2048, 1024)

**Comment by evetion** [comment]
Thanks for checking and the feedback. I've just checked now and you're right. I'll make a PR.
