### ISSUE TITLE
Failures on nightly

### ISSUE THREAD

**Issue by evetion** [yeesian/ArchGDAL.jl#375]
Currently ArchGDAL fails on 1.10, so downstream packages also fail on nightly.

@visr Do we need to build GDAL_jll again, or do we need to up its compat bounds?

```julia
 LibCURL_jll [deac9b47] log:
 ├─possible versions are: 8.0.1 or uninstalled (package in sysimage!)
 └─found to have no compatible versions left with GDAL_jll [a7073274]
   └─GDAL_jll [a7073274] log:
     ├─possible versions are: 3.0.3-301.600.200 or uninstalled
     ├─restricted by julia compatibility requirements to versions: [3.0.3-3.2.1, 300.202.100-301.600.200] or uninstalled
     └─restricted by compatibility requirements with GDAL [add2ef01] to versions: 301.600.0-301.600.200
       └─GDAL [add2ef01] log:
         ├─possible versions are: 0.1.0-1.5.1 or uninstalled
         └─restricted to versions 1.5.1-1 by ArchGDAL [c9ce4bd3], leaving only versions: 1.5.1
           └─ArchGDAL [c9ce4bd3] log:
             ├─possible versions are: 0.10.1 or uninstalled
             └─ArchGDAL [c9ce4bd3] is fixed to version 0.10.1
```

**Comment by visr** [comment]
This is probably related to nightly using a newer curl version: https://github.com/JuliaGeo/GDAL.jl/actions/runs/4542215312/jobs/8005349872?pr=150#step:5:20

**Comment by felixcremer** [comment]
Interestingly ArchGDAL 0.9.4 with a GDAL version 1.3.0 and a GDAL_jll version v300.400.100+0 works on julia nightly. 
Unfortunately I have no idea what to do with that information.

**Comment by felixcremer** [comment]
Is this an indicator, that the update of the libcurl version in the compat.toml in the Registry could help, because it seems, that GDAL_jll 300.400.100 did not restrict the LibCurl version.

**Comment by visr** [comment]
The curl issues are fixed in the registry and yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/7127
