### ISSUE TITLE
Understanding write! and RasterIO.jl example

### ISSUE THREAD

**Issue by 1oly** [yeesian/ArchGDAL.jl#39]
Hi,
Thanks for the nice work with this package! 

Just getting started and can't seem to fully understand the API. 
I'm trying to do the equivalent of this RasterIO.jl example:

```
image = fill(UInt8(127), (150, 250))

raster = RasterIO.createraster("pyrasterio/example.tif",
                                500, # width
                                300, # height
                                1, # number of bands
                                UInt8, # DataType
                                "GTiff") # Drivername

RasterIO.update!(raster,
                 image, # image to "burn" into the raster
                 1, # update band 1
                 30:180, # along (window) xcoords 30 to 180
                 50:300) # along (window) ycoords 30 to 180

RasterIO.closeraster(raster)
```
From https://github.com/wkearn/RasterIO.jl/blob/master/doc/RasterioGuide.ipynb

Since RasterIO.jl is deprecated in favour is ArchGDAL, I'm trying to follow the new write API.

Sorry for opening an issue - I'd be happy to help with documentation when I get a better grasp of the API.

Thanks

**Comment by yeesian** [comment]
Hi, thanks for the kind words!

The following should work:

```julia
using ArchGDAL; const AG = ArchGDAL

image = fill(UInt8(127), (150, 250))

# Method 1
AG.registerdrivers() do
    raster = AG.unsafe_create(
        "pyrasterio/example.tif",
        AG.getdriver("GTiff"),
        width = 500,
        height = 300,
        nbands = 1,
        dtype = UInt8
    )
    AG.write!(
        raster,
        image,  # image to "burn" into the raster
        1,      # update band 1
        30:180, # along (window) xcoords 30 to 180
        50:300  # along (window) ycoords 30 to 180
    )
    AG.destroy(raster)
end

# Method 2
AG.registerdrivers() do
    AG.create(
        "pyrasterio/example.tif",
        AG.getdriver("GTiff"),
        width = 500,
        height = 300,
        nbands = 1,
        dtype = UInt8
    ) do raster
        AG.write!(
            raster,
            image, # image to "burn" into the raster
            1, # update band 1
            30:180, # along (window) xcoords 30 to 180
            50:300 # along (window) ycoords 30 to 180
        )
    end
end
```

I'm sorry documentation has been sparse. We really can do with some help on it.

**Comment by 1oly** [comment]
Thanks! Just what I needed. Was quite close from what I could gather from the tests.

**Comment by kongdd** [comment]
Help!
This script is not work now. Because "UndefVarError: registerdrivers not defined".

**Comment by visr** [comment]
The above examples are quite dated, `registerdrivers` is no longer needed. Removing it and making the driver a keyword argument seems sufficient to get a working example again:

```julia
AG.create(
    "pyrasterio/example.tif",
    driver = AG.getdriver("GTiff"),
    width = 500,
    height = 300,
    nbands = 1,
    dtype = UInt8
) do raster
    AG.write!(
        raster,
        image, # image to "burn" into the raster
        1, # update band 1
        30:180, # along (window) xcoords 30 to 180
        50:300 # along (window) ycoords 30 to 180
    )
end
```

**Comment by kongdd** [comment]
Thank you

**Comment by Rapsodia86** [comment]
Hello, (again!)
Following the topic of write! function, I would like to ask about the compression option. 
In python I have defined function using gdal that while saving raster uses compression: 
def writeraster(data, filename, nCol, nRow, dtype, geotransform, projection):
    driver = gdal.GetDriverByName('GTiff')
    dataset = driver.Create(filename, nCol, nRow, 1, dtype, ['COMPRESS=LZW'])
    dataset.SetGeoTransform(geotransform)
    dataset.SetProjection(projection)
    #dataset.GetRasterBand(1).SetNoDataValue(-9999)
    dataset.GetRasterBand(1).WriteArray(data)
    dataset.FlushCache()
    dataset = None

Also, just using GDAL thru command line: 
>gdalwarp -overwrite -co COMPRESS=LZW file1.tif file1_LZW.tif

that changes from 120 MB to ~3 MB!

Now, how I would do this in Julia using ArchGDAL?
If I should rather open a new 'issue' about compression, please let me know.
Thank you!

**Comment by visr** [comment]
Here is an example using the same creation option that can help: https://github.com/yeesian/ArchGDAL.jl/issues/123#issuecomment-637152140

**Comment by Rapsodia86** [comment]
Works well, thank you very much!
