### ISSUE TITLE
Type of buffer in `read!` is too restricted

### ISSUE THREAD

**Issue by felixcremer** [yeesian/ArchGDAL.jl#410]
When I try to plot a Raster which is based on an ArchGDAL overview array this does not work because I can't `read!` into a PermutedDims array. See https://github.com/rafaqz/Rasters.jl/issues/596.

Can we expand the type that `read!` accepts so that we could read also into AbstractMatrix and not only Matrix?

**Comment by rafaqz** [comment]
Possible that ArchGDAL.jl is passing that to C? In which case `Array` is really needed.

**Comment by yeesian** [comment]
> Possible that ArchGDAL.jl is passing that to C?

Yes, they are being passed to C (but I can also see that it is too type-restrictive in some settings)
