### ISSUE TITLE
Can't seem to add / use ArchGDAL properly - GDAL, GDAL_jll and libgeotiff_jll seem to have some kind of issue.

### ISSUE THREAD

**Issue by jwrozelle** [yeesian/ArchGDAL.jl#427]
I've tried completely uninistalling and adding a fresh install of Julia, then using `] add ArchGDAL`

Persistently tells me

"ERROR: LoadError: InitError: could not load library "C\Users\USERNAME\\.julia\artifacts\356b5bdc540243e0fadea8d16f948dc26c1f6eeb\bin\libgeotiff.dll"

Also fails to load GDAL and GDAL_jll. I'm unclear what's happening.

I'm on Julia v1.10.3.

I've tested this on a second windows machine and am experiencing the same issue.

**Comment by visr** [comment]
This is quite unfortunate, related to new versions of GDAL_jll and PROJ_jll. This should help for now:

```
add PROJ_jll@901.300 GDAL_jll@301.800.500
```

**Comment by visr** [comment]
The broken GDAL and PROJ builds have now been yanked from the General registry, so I'm closing this. I wrote https://github.com/JuliaPackaging/Yggdrasil/issues/8781 on fixing the build script.
