### ISSUE TITLE
Import rasters to a julia array

### ISSUE THREAD

**Issue by rafaqz** [yeesian/ArchGDAL.jl#45]
Thanks for putting this package together.

I have a simple need of import tiff rasters with something better than imagemagic. It seems I can do that with this package but I'm not sure of the simplest way to just get a tiff into some kind of Julia Array. My GDAL experience is limited.

**Comment by yeesian** [comment]
Assuming you have a `.tif` file, e.g. by running
```
shell> wget https://github.com/yeesian/ArchGDALDatasets/blob/master/pyrasterio/RGB.byte.tif?raw=true
```

The following should work:

```julia
img = ArchGDAL.registerdrivers() do
    ArchGDAL.read("RGB.byte.tif") do dataset
        ArchGDAL.read(dataset)
    end
end
```
and yield
```julia
791×718×3 Array{UInt8,3}:
[:, :, 1] =
 0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  …  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00
 0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00     0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00
 0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00     0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00  0x00
 0x00
...
```

**Comment by rafaqz** [comment]
Ok thanks somehow I missed that using read twice would return an array.

**Comment by rafaqz** [comment]
Decoupling that makes sense. But it might be useful to have another package that further wraps ArchGDAL for these simple cases, so people doing basic IOcan totally avoid GDAL and just get a raster array with one command.

**Comment by yeesian** [comment]
> But it might be useful to have another package that further wraps ArchGDAL for these simple cases

Yeah, ArchGDAL is not meant to be end-user facing. It's meant for other packages to build on top of, see e.g. [`GeoDataFrames.jl`](https://github.com/yeesian/GeoDataFrames.jl)

> so people doing basic IOcan totally avoid GDAL and just get a raster array with one command.

I agree with you. Does `Images.jl` not achieve this in the interim?

**Comment by rafaqz** [comment]
Sure. I was thinking about writing something simple but I'm really not knowledgeable enough about raster data.

Unfortunately Imagemagic mangles some non-standard raster inputs on import, so its not really ok for production work.
