### ISSUE TITLE
Doesn't work with Julia 1.0

### ISSUE THREAD

**Issue by fhucho** [yeesian/ArchGDAL.jl#51]
The module fails to load with Julia 1.0, some of the reasons are that `Base.Dates` was replaced with just `Dates` or that `Void` was replaced with `missing`.

**Comment by visr** [comment]
Most of the deprecation warnings are fixed on the `juliacon` branch. If you use julia 0.7 you can use this.

For 1.0 compatibility (i.e. 0 depwarns on 0.7), we probably need to take that branch, remove the `images` work from it (for now), and update the final iterators. It takes some work, but will happen. Extra help is always appreciated :)
