### ISSUE TITLE
How do I get x and y coordinates for imported geotiff?

### ISSUE THREAD

**Issue by dldx** [yeesian/ArchGDAL.jl#52]
Hi there,

First of all, thanks for this library!

I'm trying to use Proj4 together with ArchGDAL. I have a GeoTIFF with elevation data and I would like to read it in and then get the elevation for each x,y location (in albers projection).

So I do this:
```julia
elevation_data = ArchGDAL.registerdrivers() do
           ArchGDAL.read("uk_elevation.tif") do dataset
               ArchGDAL.read(dataset, 1)
           end
       end

7714×13698 Array{UInt8,2}
```

to import the data but now I have a matrix which is unscaled. Is there a way to convert the matrix indices into the x and y coordinates that are compatible with Proj4 projected coordinates that are also in the same Albers projection? And is there a way to scale the elevation data too? I only have values between 0 and 255... hmm

The elevation file looks like this:
```
> gdalinfo uk.tif 
Driver: GTiff/GeoTIFF
Files: uk_elevation.tif
Size is 7714, 13698
Coordinate System is:
PROJCS["unnamed",
    GEOGCS["WGS 84",
        DATUM["unknown",
            SPHEROID["WGS84",6378137,298.257223563]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Albers_Conic_Equal_Area"],
    PARAMETER["standard_parallel_1",51.29427447728234],
    PARAMETER["standard_parallel_2",58.02853263411481],
    PARAMETER["latitude_of_center",0],
    PARAMETER["longitude_of_center",-4.482421875],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]
Origin = (-260204.431288259220310,6254165.336497165262699)
Pixel Size = (90.011859131968379,-90.011859131968379)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -260204.431, 6254165.336) (  9d15' 7.20"W, 60d52'11.04"N)
Lower Left  ( -260204.431, 5021182.890) (  8d 5'36.26"W, 49d48'51.47"N)
Upper Right (  434147.050, 6254165.336) (  3d27'14.14"E, 60d43'41.74"N)
Lower Right (  434147.050, 5021182.890) (  1d31'58.96"E, 49d42'25.89"N)
Center      (   86971.309, 5637674.113) (  3d 6'25.92"W, 55d24'10.38"N)
Band 1 Block=7714x1 Type=Byte, ColorInterp=Gray
  NoData Value=255
```

If I want to access data, I can use this function:
```julia
upper_left = ( -260204.431, 6254165.336)
pixel_size = 90.011859131968379

get_elevation(elevation_data, x, y) = elevation_data[Int(round((x - upper_left[1])/pixel_size)), Int(round(-(y - upper_left[2])/pixel_size))]
```

but these x & y values are completely different to what I get with Proj4... (Perhaps I should be posting this in Proj4's issues instead.)

Sorry if this is a silly question but I'm unfamiliar with geodata :( 

Thanks in advance!

**Comment by visr** [comment]
From the `gdalinfo` it seems that your GeoTIFF is already in the same projections as the one you want to use, or not? If so that would mean no converting from one projection to another is needed, so no need for Proj4.

I think wanting to sample a raster based on an x/y location is common enough that we probably should add convenience functions for it.

```julia
using ArchGDAL

elevation_data, geotransform = ArchGDAL.registerdrivers() do
   ArchGDAL.read("utmsmall.tif") do dataset
       ArchGDAL.read(dataset, 1),
       ArchGDAL.getgeotransform(dataset)
   end
end

x_min = geotransform[1]
x_res = geotransform[2]
y_max = geotransform[4]
y_res = geotransform[6]

row_index(y::Number) = Int(fld(y - y_max, y_res)) + 1
column_index(x::Number) = Int(fld(x - x_min, x_res)) + 1

function get_elevation(elevation_data, x, y)
    r = row_index(x)
    c = column_index(x)
    elevation_data[r, c]
end

get_elevation(elevation_data, x, y)
```

**Comment by dldx** [comment]
Hey @visr, thanks for the reply and the code! I guess ArchGDAL isn't the issue then. I already converted this geotiff into the right projection using gdalwarp but I have lat/long coordinates that I am converting with Proj4 using an identical string and getting different values.

```
gdalwarp -t_srs "+proj=aea +ellps=WGS84 +lat_1=51.29427447728234 +lat_2=58.02853263411481 +lon_0=-4.482421875" -overwrite w001001.adf uk_elevation.tif
```

and:

```julia
wgs84 = Projection("+proj=longlat +datum=WGS84 +no_defs")
aea = Projection("+proj=aea +ellps=WGS84 +lat_1=51.29427447728234 +lat_2=58.02853263411481 +lon_0=-4.482421875")
Proj4.transform(wgs84, aea, convert(Array, station_data[[:long, :lat]]))
```

I'm pretty sure the points are projected correctly but the scale is of, presumably because I need to include a bounding box with Proj4 somehow?

**Comment by visr** [comment]
In the `gdalwarp` command you don't specifiy a `-s_srs`, in Proj4 you do. If it is not in the source file, this could go wrong. Not sure if that's it though. What do you mean by the scale is off?

I would expect that if you use Proj4.jl to project the corners of your raster, you should get the same results as what `gdalwarp` does. There's no need for a bounding box. How do they differ?

**Comment by dldx** [comment]
I finally figured out my mistake. It was that I was converting lat, long data using the wrong projection.

The correct code is:
```julia
latlong_airy = Proj4.Projection("+proj=longlat +ellps=airy +towgs84=0,0,0 +no_defs")
aea = Projection("+proj=aea +ellps=WGS84 +lat_1=51.29427447728234 +lat_2=58.02853263411481 +lon_0=-4.482421875")
Proj4.transform(latlong_airy, aea, convert(Array, station_data[[:long, :lat]]))
```

With this, GDAL and Proj4 match perfectly :) 

Thanks for the help!
