### ISSUE TITLE
Support rasterization of vector objects

### ISSUE THREAD

**Issue by yeesian** [yeesian/ArchGDAL.jl#55]
following the discussion in https://discourse.julialang.org/t/how-can-i-rasterize-the-polygons-of-a-shapefile-in-julia/15089/2 and incorporating the [GDAL/OGR cookbook example](http://pcjericks.github.io/py-gdalogr-cookbook/raster_layers.html#convert-an-ogr-file-to-a-raster).

**Comment by visr** [comment]
Ideally of course we'll have support for all GDAL utilities. Though don't want to hijack this issue for that ;)
https://github.com/JuliaGeo/GDAL.jl/issues/37
