### ISSUE TITLE
Simplify the creation of new datasets

### ISSUE THREAD

**Issue by yeesian** [yeesian/ArchGDAL.jl#56]
An example in http://geoexamples.blogspot.com/2012/01/creating-files-in-ogr-and-gdal-with.html.

I'm also starting to feel that we should support a more REPL friendly version of `ArchGDAL.read(filename)` that just reads and copies the original dataset into an in-memory dataset for exploration. Expert users can still use the do-block version for out-of-core processing.

**Comment by visr** [comment]
Yeah I think that's a good idea as well. Very often all I need is a short running (maybe even throwaway) script and don't care so much about the cleanup.

**Comment by pritamd47** [comment]
I think this issue has been dealt with. Can be closed?
