### ISSUE TITLE
Add support for getproperty?

### ISSUE THREAD

**Issue by yeesian** [yeesian/ArchGDAL.jl#63]
https://docs.julialang.org/en/v1/base/base/index.html#Base.getproperty

**Comment by visr** [comment]
For which types do you think it might make sense to do this? I'm a bit reserved about this, since it's not very julian, it's mainly added for things like `PyCall` and `DataFrames df.col`. You don't want to end up in a situation where it's not clear whether to use `f(x)` or `x.f`.

**Comment by yeesian** [comment]
Yeah, there's no real compelling reason for it in this package for now
