### ISSUE TITLE
wkbUnknown not defined when creating layer with default geom?

### ISSUE THREAD

**Issue by cchderrick** [yeesian/ArchGDAL.jl#64]
Here is the code that should reproduce the error.
```julia
ArchGDAL.registerdrivers() do
    drv = ArchGDAL.getdriver("ESRI Shapefile")
    ArchGDAL.create("test",drv) do ds

        layer = ArchGDAL.createlayer(ds,"test") # UndefVarError: wkbUnknown not defined
        # layer = ArchGDAL.createlayer(ds,"test", geom=ArchGDAL.GDAL.wkbUnknown) # This seems to  work
        ...
    end
end
```
the problem seems to be at `dataset.jl` [line 315]([https://github.com/yeesian/ArchGDAL.jl/blob/a1f167dec845df058d36e650f5e871eeb40a1e1c/src/dataset.jl#L315])

**Comment by visr** [comment]
Ah yes, that should be GDAL.wkbUnknown there. Would you like to change it? Much appreciated!

This bug aside, I would guess that in most cases you would not want to use an unknown geometry type. Not sure how well it works inside GDAL.

**Comment by cchderrick** [comment]
noted, thank you. I didn't know how to reference different geometry type at first, just trying to get it to write some shapefiles.
