### ISSUE TITLE
How to extract longitude and latitude from a geoTIFF?

### ISSUE THREAD

**Issue by sethmb** [yeesian/ArchGDAL.jl#68]
Hello,

First of all, thank you developers for all the hard work!

I have an image of a traffic density heat map that I have georeferenced and exported as a geoTIFF. I  am now trying to extract the longitude and latitude values from that georeferenced image using Julia. I am reasonably new to Julia programming and geodata, so a lot of the documentation is going over my head. 

Is this something that ArchGDAL can be used for? If so, how? The documentation available does provide some hints on how to do it but there are no easy to follow examples.

My apologies for the beginner questions.

Cheers!

**Comment by yeesian** [comment]
This is not currently documented. One way of doing it (using [utmsmall.tif](https://github.com/yeesian/ArchGDALDatasets/blob/master/data/utmsmall.tif) as an example) is:

```julia
import ArchGDAL, GeoInterface
const AG = ArchGDAL

function px2xy(gt, x, y)
    xoff, a, b, yoff, d, e = gt
    xp = a * (x + 0.5) + b * (y + 0.5) + xoff
    yp = d * (x + 0.5) + e * (y + 0.5) + yoff
    AG.createpoint(xp, yp)
end

lnglats = AG.registerdrivers() do
    AG.read("utmsmall.tif") do ds
        geotransform = AG.getgeotransform(ds)
        spatialref = AG.importWKT(AG.getproj(ds))
        AG.createcoordtrans(spatialref, AG.importEPSG(4326)) do transform
            [
                GeoInterface.coordinates(
                    AG.transform!(px2xy(geotransform,i,j), transform)
                )
                for i in 1:AG.width(ds), j in 1:AG.height(ds)
            ]
        end
    end
end
```

**Comment by sethmb** [comment]
Thank you very much! The code worked as expected.
