### ISSUE TITLE
Tag Julia 0.6 version

### ISSUE THREAD

**Issue by mauro3** [yeesian/ArchGDAL.jl#70]
Could you put a tag on bbe15b66cde73bb07f4e35909, maybe v0.0.0, as that this the last commit which works with Julia  0.6.  For me there is no need to register it with METADATA (although attobot might do it anyway).

**Comment by yeesian** [comment]
Can I check if https://github.com/yeesian/ArchGDAL.jl/releases/tag/v0.0.0 works for you? Github only allows tagging from branches, so I traced it back to the PR preceding bbe15b6

**Comment by mauro3** [comment]
Thanks!  This does what it should (but I still need to figure out how to run travis with it...)
