### ISSUE TITLE
Add support for GDAL utilities

### ISSUE THREAD

**Issue by yeesian** [yeesian/ArchGDAL.jl#74]
Will make it easier to port online examples/tutorials for GDAL when working on things like https://github.com/yeesian/ArchGDAL.jl/issues/40#issuecomment-452716783

**Comment by visr** [comment]
(I know you know this @yeesian but for context or if someone wants to contribute)

Copying from GDAL.jl's README [here](https://github.com/JuliaGeo/GDAL.jl#using-the-gdal-and-ogr-utilities):

> Since GDAL 2.1's [RFC59.1](https://trac.osgeo.org/gdal/wiki/rfc59.1_utilities_as_a_library) most utilities are also available as functions in the library, they are implemented [here](https://github.com/JuliaGeo/GDAL.jl/blob/master/src/gdal_utils.jl) and tested [here](https://github.com/JuliaGeo/GDAL.jl/blob/master/test/gdal_utils.jl). If these are used you can avoid the need for calling the binaries.

This is basically about creating a friendlier interface to these utilities, similar to how ArchGDAL already creates a friendlier interface around much of the rest of GDAL.
