### ISSUE TITLE
How to read and write wkb with srid?

### ISSUE THREAD

**Issue by huaxk** [yeesian/ArchGDAL.jl#77]
As shown in the title, give some examples，thanks!

**Comment by huaxk** [comment]
```
p = AG.fromWKT("Point(2 3)")
ref = AG.importEPSG(4326)
AG.setspatialref!(p, AG.SpatialRef(ref.ptr))
AG.toWKB(p) |> bytes2hex
```
output hex string:
`"010100000000000000000000400000000000000840"`
spatialref information is not saved! 
expected wkb string with spattialref:
`"0101000020E610000000000000000000400000000000000840"`
how to save it?

**Comment by huaxk** [comment]
```
wkb = hex2bytes("0101000020E610000000000000000041400000000000804A40")
ref = AG.importEPSG(4326)
AG.fromWKB(wkb, ref)
```
ERROR: GDALError (CE_Failure, code 6):
        Unsupported WKB type 536870913

the wkb spatialref is epsg 4326, why is it wrong?

**Comment by yeesian** [comment]
I don't think GDAL currently supports "non-standard" WKT/WKB formats yet. The latest that I know of came from https://trac.osgeo.org/gdal/wiki/rfc49_curve_geometries

**Comment by huaxk** [comment]
```
function unsafe_fromWKB(
        ::Type{G},
        data,
        spatialref::AbstractSpatialRef = SpatialRef(C_NULL)
    ) where G <: AbstractGeometry
```
`spatialref`: handle to the spatial reference to be assigned to the created
    geometry object. This may be `NULL` (default).

how to use param spatialref?

**Comment by yeesian** [comment]
This package does not currently provide support for reading and writing WKT with SRID. That functionality will need to be implemented, since it is not provided by the base GDAL library.

**Comment by huaxk** [comment]
That's right！ Functionality of reading and writing EWKT/EWKB can be implemented by LibGEOS.jl, i am working on it.

**Comment by yeesian** [comment]
Linking to https://github.com/JuliaGeo/LibGEOS.jl/issues/60 for context in this thread.
