### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by yeesian** [yeesian/ArchGDAL.jl#82]
In particular, for

- [ ] src/base/display.jl (test/test_display.jl)
- [ ] src/ogr/featurelayer.jl (test/test_featurelayer.jl)
- [ ] src/ogr/geometry.jl (test/test_geometry.jl)
- [ ] src/raster/rasterio.jl (test/test_rasterio.jl)
- [ ] src/spatialref.jl (test/test_spatialref.jl) ~~# to be added to test/runtests.jl~~

**Comment by visr** [comment]
I'll close this now that after #76 test coverage will be above 90% (quite impressive).

From the [![Coverage Status](https://coveralls.io/repos/github/yeesian/ArchGDAL.jl/badge.svg?branch=master)](https://coveralls.io/github/yeesian/ArchGDAL.jl?branch=master) on the README we can quite easily track files that could still be improved, here are the ones below 75% as of now:

src/raster/rasterio.jl - 65%
src/gcp.jl	- 0%
