### ISSUE TITLE
Add readgeotiff util function?

### ISSUE THREAD

**Issue by juliohm** [yeesian/ArchGDAL.jl#88]
What do you think of a utility function to read bands from geo tiff files?

```julia
using ArchGDAL

function readgeotiff(fname, bands=1)
    ArchGDAL.registerdrivers() do
        ArchGDAL.read(fname) do dataset
            ArchGDAL.read(dataset, bands)
        end
    end
end
```

I am using it all the time, maybe it could be part of ArchGDAL.jl?

**Comment by evetion** [comment]
Over in #76 it will become easier (reduce the `do` to do the above.) Note that your utility is not specific to geotiffs and will happily read any supported driver into the first band.

Shameless plug, you can have a try with my own package [GeoArrays.jl](https://github.com/evetion/GeoArrays.jl) which has a similar aim as your utility function.

**Comment by juliohm** [comment]
Wasn't aware of GeoArrays.jl @evetion , thanks for sharing. Will take a look now, it seems very useful. One thing I realised with the function above is that the crs is not taken into account, and the coordinates I get are rotated when I load with ArchGDAL.jl. I am probably missing some post-processing step after loading to fix the coordinate system.

**Comment by juliohm** [comment]
Closing the issue for now.

**Comment by yeesian** [comment]
> One thing I realised with the function above is that the crs is not taken into account, and the coordinates I get are rotated when I load with ArchGDAL.jl. I am probably missing some post-processing step after loading to fix the coordinate system.

Yeah sorry about that. I'm not sure how much it'll help, but we have a branch for reading rasters into something compatible with JuliaImages: https://github.com/yeesian/ArchGDAL.jl/commit/e3eaa0f5d6ead3b154f9065aea8ef8b9dde45ed4, which I had been putting off until #76 is done. Along the way, we decided GeoRasters is probably the better place/package to figure out how it should work.
