### ISSUE TITLE
minimum julia version

### ISSUE THREAD

**Issue by visr** [yeesian/ArchGDAL.jl#9]
Would you like to support 0.4? I'd like to know before I get rid of some deprecation warnings. (For me it's not necessary.)

**Comment by yeesian** [comment]
I'm currently still on 0.4, but will like to move to 0.5 soon, and don't have plans to maintain support for 0.4 after I do. What are your plans for GDAL.jl?

**Comment by visr** [comment]
Yes I'm in the process of moving as well, and have similar plans for GDAL.jl. I'll make a PR using Compat, then we can remove it again once we transitioned.

**Comment by yeesian** [comment]
closed by #12
