### ISSUE TITLE
read! and write! argument order

### ISSUE THREAD

**Issue by rafaqz** [yeesian/ArchGDAL.jl#90]
Julia methods with a ! bang normally write to the first argument. It would be easier to understand  if they did here too. Its hard to tell when the buffer or Dataset etc is being written to.

**Comment by rafaqz** [comment]
Seems `read!` has irregular syntax everywhere.

**Comment by rafaqz** [comment]
I looked at the style guide 
https://docs.julialang.org/en/v1/manual/style-guide/index.html#Write-functions-with-argument-ordering-similar-to-Julia-Base-1

`read` seems to use this syntax everywhere because `IO`  streams are meant to go before the array to write to. So it also kind of makes sense for Dataset to be fist because that's how all the `read` methods normally look, I just rarely use `read` so I'm not used to it... An example in Base - filename is the first arg even though its not `IO` so standard form of `read` seems to win over the style guide.

```julia
help?> HDF5.read!
  read!(stream::IO, array::Union{Array, BitArray})
  read!(filename::AbstractString, array::Union{Array, BitArray})
```

**Comment by yeesian** [comment]
Ah that makes sense, thanks for the explanation
